Add main.rs to run it standalone
zkat/is_ci pull request #2
Opened 2022-09-27 18:50 UTC by 6543

just print `true` or `false` to std

nice if you like to have integration tests, etc ...

2022-09-27 19:39 UTC, 6543 commented
@zkat is that ok for the repo?

2022-09-27 19:56 UTC, zkat commented
I think that's fine

2022-09-29 13:38 UTC, 6543 commented
anything missing?

2022-09-29 16:50 UTC, zkat commented
Like I said, I would rather this use exit codes instead of stdout. I'm waiting for that change.

2022-09-29 17:03 UTC, 6543 commented
your review might be still "pending" ... because i didn't see any message about that ... but will ajust the pull

2022-09-29 17:16 UTC, 6543 commented
@zkat done ...

2022-09-29 17:38 UTC, zkat requested changes

2022-09-29 17:38 UTC, zkat commented on src/main.rs
> +    println!("{}", is_ci);
My preference is for this to use exit codes instead of output, like `true(1)` and `false(1)`.

2022-09-29 17:38 UTC, zkat commented on src/main.rs
> +    std::process::exit(1);
```suggestion
    let code = if uncached() { 0 } else { 1 };
    std::process::exit(code);
```

2022-09-29 17:38 UTC, zkat commented on src/main.rs
> +    std::process::exit(1);
your code will always return 0 right now. Please update it.

2022-09-29 22:25 UTC, 6543 commented
well my "more compact" did broke it but your's is as compact and works ...

2022-09-29 22:36 UTC, zkat approved these changes

2022-09-29 22:37 UTC, merged